/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminFormsRouteImport } from './routes/admin.forms'
import { Route as AdminKioskRouteImport } from './routes/admin.kiosk'
import { Route as AdminResponsesRouteImport } from './routes/admin.responses'
import { Route as SSessionRouteImport } from './routes/s.$session'
import { Route as AdminResponsesIdRouteImport } from './routes/admin.responses_.$id'
import { Route as SSessionIndexRouteImport } from './routes/s.$session.index'
import { Route as SSessionBasicRouteImport } from './routes/s.$session.basic'
import { Route as SSessionCompleteRouteImport } from './routes/s.$session.complete'
import { Route as SSessionConditionRouteImport } from './routes/s.$session.condition'
import { Route as SSessionPreferenceRouteImport } from './routes/s.$session.preference'
import { Route as SSessionReviewRouteImport } from './routes/s.$session.review'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFormsRoute = AdminFormsRouteImport.update({
  id: '/forms',
  path: '/forms',
  getParentRoute: () => AdminRoute,
} as any)
const AdminKioskRoute = AdminKioskRouteImport.update({
  id: '/kiosk',
  path: '/kiosk',
  getParentRoute: () => AdminRoute,
} as any)
const AdminResponsesRoute = AdminResponsesRouteImport.update({
  id: '/responses',
  path: '/responses',
  getParentRoute: () => AdminRoute,
} as any)
const SSessionRoute = SSessionRouteImport.update({
  id: '/s/$session',
  path: '/s/$session',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminResponsesIdRoute = AdminResponsesIdRouteImport.update({
  id: '/responses_/$id',
  path: '/responses/$id',
  getParentRoute: () => AdminRoute,
} as any)
const SSessionIndexRoute = SSessionIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SSessionRoute,
} as any)
const SSessionBasicRoute = SSessionBasicRouteImport.update({
  id: '/basic',
  path: '/basic',
  getParentRoute: () => SSessionRoute,
} as any)
const SSessionCompleteRoute = SSessionCompleteRouteImport.update({
  id: '/complete',
  path: '/complete',
  getParentRoute: () => SSessionRoute,
} as any)
const SSessionConditionRoute = SSessionConditionRouteImport.update({
  id: '/condition',
  path: '/condition',
  getParentRoute: () => SSessionRoute,
} as any)
const SSessionPreferenceRoute = SSessionPreferenceRouteImport.update({
  id: '/preference',
  path: '/preference',
  getParentRoute: () => SSessionRoute,
} as any)
const SSessionReviewRoute = SSessionReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => SSessionRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/forms': typeof AdminFormsRoute
  '/admin/kiosk': typeof AdminKioskRoute
  '/admin/responses': typeof AdminResponsesRoute
  '/s/$session': typeof SSessionRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/admin/responses/$id': typeof AdminResponsesIdRoute
  '/s/$session/basic': typeof SSessionBasicRoute
  '/s/$session/complete': typeof SSessionCompleteRoute
  '/s/$session/condition': typeof SSessionConditionRoute
  '/s/$session/preference': typeof SSessionPreferenceRoute
  '/s/$session/review': typeof SSessionReviewRoute
  '/s/$session/': typeof SSessionIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/forms': typeof AdminFormsRoute
  '/admin/kiosk': typeof AdminKioskRoute
  '/admin/responses': typeof AdminResponsesRoute
  '/admin': typeof AdminIndexRoute
  '/admin/responses/$id': typeof AdminResponsesIdRoute
  '/s/$session/basic': typeof SSessionBasicRoute
  '/s/$session/complete': typeof SSessionCompleteRoute
  '/s/$session/condition': typeof SSessionConditionRoute
  '/s/$session/preference': typeof SSessionPreferenceRoute
  '/s/$session/review': typeof SSessionReviewRoute
  '/s/$session': typeof SSessionIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/forms': typeof AdminFormsRoute
  '/admin/kiosk': typeof AdminKioskRoute
  '/admin/responses': typeof AdminResponsesRoute
  '/s/$session': typeof SSessionRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/admin/responses_/$id': typeof AdminResponsesIdRoute
  '/s/$session/basic': typeof SSessionBasicRoute
  '/s/$session/complete': typeof SSessionCompleteRoute
  '/s/$session/condition': typeof SSessionConditionRoute
  '/s/$session/preference': typeof SSessionPreferenceRoute
  '/s/$session/review': typeof SSessionReviewRoute
  '/s/$session/': typeof SSessionIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/admin/dashboard'
    | '/admin/forms'
    | '/admin/kiosk'
    | '/admin/responses'
    | '/s/$session'
    | '/admin/'
    | '/admin/responses/$id'
    | '/s/$session/basic'
    | '/s/$session/complete'
    | '/s/$session/condition'
    | '/s/$session/preference'
    | '/s/$session/review'
    | '/s/$session/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin/dashboard'
    | '/admin/forms'
    | '/admin/kiosk'
    | '/admin/responses'
    | '/admin'
    | '/admin/responses/$id'
    | '/s/$session/basic'
    | '/s/$session/complete'
    | '/s/$session/condition'
    | '/s/$session/preference'
    | '/s/$session/review'
    | '/s/$session'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/admin/dashboard'
    | '/admin/forms'
    | '/admin/kiosk'
    | '/admin/responses'
    | '/s/$session'
    | '/admin/'
    | '/admin/responses_/$id'
    | '/s/$session/basic'
    | '/s/$session/complete'
    | '/s/$session/condition'
    | '/s/$session/preference'
    | '/s/$session/review'
    | '/s/$session/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
  SSessionRoute: typeof SSessionRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/forms': {
      id: '/admin/forms'
      path: '/forms'
      fullPath: '/admin/forms'
      preLoaderRoute: typeof AdminFormsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/kiosk': {
      id: '/admin/kiosk'
      path: '/kiosk'
      fullPath: '/admin/kiosk'
      preLoaderRoute: typeof AdminKioskRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/responses': {
      id: '/admin/responses'
      path: '/responses'
      fullPath: '/admin/responses'
      preLoaderRoute: typeof AdminResponsesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/s/$session': {
      id: '/s/$session'
      path: '/s/$session'
      fullPath: '/s/$session'
      preLoaderRoute: typeof SSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/responses_/$id': {
      id: '/admin/responses_/$id'
      path: '/responses/$id'
      fullPath: '/admin/responses/$id'
      preLoaderRoute: typeof AdminResponsesIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/s/$session/': {
      id: '/s/$session/'
      path: '/'
      fullPath: '/s/$session/'
      preLoaderRoute: typeof SSessionIndexRouteImport
      parentRoute: typeof SSessionRoute
    }
    '/s/$session/basic': {
      id: '/s/$session/basic'
      path: '/basic'
      fullPath: '/s/$session/basic'
      preLoaderRoute: typeof SSessionBasicRouteImport
      parentRoute: typeof SSessionRoute
    }
    '/s/$session/complete': {
      id: '/s/$session/complete'
      path: '/complete'
      fullPath: '/s/$session/complete'
      preLoaderRoute: typeof SSessionCompleteRouteImport
      parentRoute: typeof SSessionRoute
    }
    '/s/$session/condition': {
      id: '/s/$session/condition'
      path: '/condition'
      fullPath: '/s/$session/condition'
      preLoaderRoute: typeof SSessionConditionRouteImport
      parentRoute: typeof SSessionRoute
    }
    '/s/$session/preference': {
      id: '/s/$session/preference'
      path: '/preference'
      fullPath: '/s/$session/preference'
      preLoaderRoute: typeof SSessionPreferenceRouteImport
      parentRoute: typeof SSessionRoute
    }
    '/s/$session/review': {
      id: '/s/$session/review'
      path: '/review'
      fullPath: '/s/$session/review'
      preLoaderRoute: typeof SSessionReviewRouteImport
      parentRoute: typeof SSessionRoute
    }
  }
}

interface AdminRouteChildren {
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminFormsRoute: typeof AdminFormsRoute
  AdminKioskRoute: typeof AdminKioskRoute
  AdminResponsesRoute: typeof AdminResponsesRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminResponsesIdRoute: typeof AdminResponsesIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminDashboardRoute: AdminDashboardRoute,
  AdminFormsRoute: AdminFormsRoute,
  AdminKioskRoute: AdminKioskRoute,
  AdminResponsesRoute: AdminResponsesRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminResponsesIdRoute: AdminResponsesIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface SSessionRouteChildren {
  SSessionBasicRoute: typeof SSessionBasicRoute
  SSessionCompleteRoute: typeof SSessionCompleteRoute
  SSessionConditionRoute: typeof SSessionConditionRoute
  SSessionPreferenceRoute: typeof SSessionPreferenceRoute
  SSessionReviewRoute: typeof SSessionReviewRoute
  SSessionIndexRoute: typeof SSessionIndexRoute
}

const SSessionRouteChildren: SSessionRouteChildren = {
  SSessionBasicRoute: SSessionBasicRoute,
  SSessionCompleteRoute: SSessionCompleteRoute,
  SSessionConditionRoute: SSessionConditionRoute,
  SSessionPreferenceRoute: SSessionPreferenceRoute,
  SSessionReviewRoute: SSessionReviewRoute,
  SSessionIndexRoute: SSessionIndexRoute,
}

const SSessionRouteWithChildren = SSessionRoute._addFileChildren(
  SSessionRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
  SSessionRoute: SSessionRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
